version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SuaSenhaForte123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  api:
    build: .
    depends_on:
      - db
    ports:
      - "5000:80"
